name: Run Go tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
       - 'go/**'
  # Want to trigger these tests whenever the attestation
  # libraries are regenerated, or new modules/tests are
  # added to the language bindings
  pull_request:
      paths:
          - 'go/**'
permissions: read-all
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Install Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version: 1.20.x
      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      - name: Setup Env
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Run tests
        run: |
          make go_test
